rules = {'I want (.*)': ['What would it mean if you got {0}',
  'Why do you want {0}',
  "What's stopping you from getting {0}"],
 'do you remember (.*)': ['Did you think I would forget {0}',
  "Why haven't you been able to forget {0}",
  'What about {0}',
  'Yes .. and?'],
 'do you think (.*)': ['if {0}? Absolutely.', 'No chance'],
 'if (.*)': ["Do you really think it's likely that {0}",
  'Do you wish that {0}',
  'What do you think about {0}',
  'Really--if {0}']}

rules_de = {
  'Ich will (.*)': ['Was wuerdest du sagen wenn du {0} bekommst?',
  'Warum willst du {0}?',
  'Was haelt dich davon ab {0} zu besorgen?'],
 'Erinnerst du dich an (.*)': ['Denkst du ich wuerde {0} vergessen',
  'Wie koennte ich {0} vergessen',
  'Was ist mit {0}',
  'Ja klar!'],
 'Denkst du (.*)': ['{0}? Ja, denke ich schon.', 'Nein, denke ich nicht'],
 'wenn (.*)': ["Denkst du wirklich es ist moeglich, dass {0}?",
  'Wuenscht du dass {0}?',
  'Was denkst du darueber wenn {0}?'],
  'Wie (.*)': ['Wieso willst du das wissen?'],
  'hei(ss|ß)e (.*)': ['Sehr schöner Name.'],
  'Name ist (.*)': ['Das ist aber ein schöner Name.', '{0} ist aber ein schöner Name.' ],
  'Wie hei(ss|ß)t du': ['Ich heiße Bot', 'Man nennt micht Bot', 'Mein Name ist Bot und wie heißt du?'],
}