rules = {'I want (.*)': ['What would it mean if you got {0}',
  'Why do you want {0}',
  "What's stopping you from getting {0}"],
 'do you remember (.*)': ['Did you think I would forget {0}',
  "Why haven't you been able to forget {0}",
  'What about {0}',
  'Yes .. and?'],
 'do you think (.*)': ['if {0}? Absolutely.', 'No chance'],
 'if (.*)': ["Do you really think it's likely that {0}",
  'Do you wish that {0}',
  'What do you think about {0}',
  'Really--if {0}']}

rules_de = {
  'ich will (.*)': ['Was würdest du sagen wenn du {0} bekommst?',
                    'Warum willst du {0}?',
                    'Was hält dich davon ab {0} zu besorgen?'],
 'erinnerst du dich an (.*)': ['Denkst du ich wuerde {0} vergessen',
                               'Wie koennte ich {0} vergessen',
                               'Was ist mit {0}',
                               'Ja klar!'],
 'denkst du (.*)': ['{0}? Ja, denke ich schon.',
                    'Nein, denke ich nicht'],
 'wenn (.*)': ["Denkst du wirklich es ist moeglich, dass {0}?",
               'Wünscht du dass {0}?',
               'Was denkst du darueber wenn {0}?'],
  'wie (.*)': ['Wieso willst du das wissen?'],
  'warum (.*)': ['Ich weiß leider auch nicht warum {0}',
                 'Das ist eine gute Frage warum {0}'],
  'woher (.*)': ['Ich weiß leider auch nicht woher {0}',
                 'Das ist eine gute Frage woher {0}'],
  'heisse (.*)': ['Hallo {0}',
                  'Hi {0}',
                  'Hallo {0}, schön dich kennenzulernen'],
  'heiße (.*)': ['Hallo {0}',
                 'Hi {0}',
                 'Hallo {0}, schön dich kennenzulernen'],
  'name ist (.*)': ['Hallo {0}',
                    'Hi {0}',
                    'Hallo {0}, schön dich kennenzulernen'],
  'wie hei(ss|ß)t du': ['Ich heiße Bot',
                        'Man nennt mich Bot',
                        'Mein Name ist Bot und wie heißt du?'],
  'weil (.*)': ['Das ist deine Meinung.'],
  'weil ich (.*)': ['Hm ok'],
  '(hallo|hi|hello|servus)': ['{0}',
                              'Hi!',
                              'Hi wie geht es dir?',
                              'Hallo, schön mal wieder von dir zu hören'],
  'mir geht es .*(gut|hervorragend|grandios|super)': ['Das freut mich zu hören',
                                                      'Super, weiter so'],
  'mir geht es .*(schlecht|nicht gut)': ['Warum geht es dir {0}?']
}
